#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_ROOT="${XDG_CONFIG_HOME:-$HOME/.config}/hypr-material3"
HYPR_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
SWAYNC_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/swaync"
TARGET_HYPR_CONF="$HYPR_DIR/hyprland.conf"
BACKUP_SUFFIX="$(date +%Y%m%d-%H%M%S)"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Missing dependency: %s\n' "$1"
    return 1
  fi
}

printf 'Installing Material 3 Hyprland theme into %s\n' "$TARGET_ROOT"

mkdir -p "$TARGET_ROOT"
mkdir -p "$HYPR_DIR"
mkdir -p "$SWAYNC_DIR"

if [ -d "$TARGET_ROOT/hypr" ] || [ -d "$TARGET_ROOT/rofi" ] || [ -d "$TARGET_ROOT/anyrun" ] || [ -d "$TARGET_ROOT/swaync" ] || [ -d "$TARGET_ROOT/wallpapers" ]; then
  cp -r "$TARGET_ROOT" "${TARGET_ROOT}.backup-$BACKUP_SUFFIX"
  printf 'Backed up existing theme directory to %s.backup-%s\n' "$TARGET_ROOT" "$BACKUP_SUFFIX"
fi

cp -r "$PROJECT_DIR/config/." "$TARGET_ROOT/"
cp -r "$PROJECT_DIR/scripts" "$TARGET_ROOT/"
if [ -d "$PROJECT_DIR/wallpapers" ]; then
  mkdir -p "$TARGET_ROOT/wallpapers"
  cp -r "$PROJECT_DIR/wallpapers/." "$TARGET_ROOT/wallpapers/"
fi

if [ -f "$SWAYNC_DIR/config.json" ] || [ -f "$SWAYNC_DIR/style.css" ]; then
  mkdir -p "${SWAYNC_DIR}.backup-$BACKUP_SUFFIX"
  [ -f "$SWAYNC_DIR/config.json" ] && cp "$SWAYNC_DIR/config.json" "${SWAYNC_DIR}.backup-$BACKUP_SUFFIX/"
  [ -f "$SWAYNC_DIR/style.css" ] && cp "$SWAYNC_DIR/style.css" "${SWAYNC_DIR}.backup-$BACKUP_SUFFIX/"
fi
cp "$PROJECT_DIR/config/swaync/config.json" "$SWAYNC_DIR/config.json"
cp "$PROJECT_DIR/config/swaync/style.css" "$SWAYNC_DIR/style.css"

chmod +x "$TARGET_ROOT/scripts/"*.sh

if [ -f "$TARGET_HYPR_CONF" ] && ! grep -Fq "source = $TARGET_ROOT/hypr/hyprland.conf" "$TARGET_HYPR_CONF"; then
  cp "$TARGET_HYPR_CONF" "$TARGET_HYPR_CONF.backup-$BACKUP_SUFFIX"
  printf 'Backed up existing Hyprland config to %s.backup-%s\n' "$TARGET_HYPR_CONF" "$BACKUP_SUFFIX"
fi

cat > "$TARGET_HYPR_CONF" <<EOF
# Generated by the Material 3 Hyprland installer.
source = $TARGET_ROOT/hypr/hyprland.conf
EOF

printf '\nDependency check:\n'
MISSING=0
for cmd in Hyprland hyprpaper swaync anyrun rofi ghostty nautilus waybar playerctl; do
  if require_cmd "$cmd"; then
    printf '  [ok] %s\n' "$cmd"
  else
    printf '  [!!] %s\n' "$cmd"
    MISSING=1
  fi
done

printf '\nInstalled files:\n'
printf '  %s\n' "$TARGET_ROOT/hypr/hyprland.conf"
printf '  %s\n' "$TARGET_ROOT/hypr/hyprlock.conf"
printf '  %s\n' "$TARGET_ROOT/hypr/keybinds.conf"
printf '  %s\n' "$TARGET_ROOT/hypr/apps.conf"
printf '  %s\n' "$TARGET_ROOT/swaync/config.json"
printf '  %s\n' "$TARGET_ROOT/anyrun/config.ron"
printf '  %s\n' "$TARGET_ROOT/rofi/material3.rasi"
printf '  %s\n' "$TARGET_ROOT/waybar/config.jsonc"
printf '  %s\n' "$TARGET_ROOT/wallpapers"

if [ "$MISSING" -eq 1 ]; then
  printf '\nInstall completed, but some required apps are missing.\n'
  printf 'Install them with your package manager, then restart Hyprland.\n'
else
  if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ] && [ -n "${WAYLAND_DISPLAY:-}" ]; then
    hyprctl reload >/dev/null 2>&1 || true
    hyprctl dispatch exec "$TARGET_ROOT/scripts/launch-hyprpaper.sh" >/dev/null 2>&1 || true
    hyprctl dispatch exec "$TARGET_ROOT/scripts/launch-swaync.sh" >/dev/null 2>&1 || true
    hyprctl dispatch exec "$TARGET_ROOT/scripts/launch-waybar.sh" >/dev/null 2>&1 || true
    printf '\nInstall completed. Live services were refreshed in the current Hyprland session.\n'
  else
    printf '\nInstall completed. Restart Hyprland to apply the theme.\n'
  fi
fi
