$terminal = ghostty
$fileManager = nautilus
$menu = @PYPRLAND_DATA_DIR@/scripts/launch-anyrun.sh
$quickRunner = @PYPRLAND_DATA_DIR@/scripts/launch-rofi.sh
$mediaController = @PYPRLAND_DATA_DIR@/scripts/launch-media-controller.sh
