$terminal = ghostty
$fileManager = nautilus
$menu = @HYPRCAT_DATA_DIR@/scripts/launch-anyrun.sh
$quickRunner = @HYPRCAT_DATA_DIR@/scripts/launch-rofi.sh
$mediaController = @HYPRCAT_DATA_DIR@/scripts/launch-media-controller.sh
