$terminal = ghostty
$fileManager = nautilus
$menu = ~/.config/hypr-material3/scripts/launch-anyrun.sh
$quickRunner = ~/.config/hypr-material3/scripts/launch-rofi.sh
$mediaController = ~/.config/hypr-material3/scripts/launch-media-controller.sh
