exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = @PYPRLAND_DATA_DIR@/scripts/launch-hyprpaper.sh
exec-once = @PYPRLAND_DATA_DIR@/scripts/launch-swaync.sh
exec-once = @PYPRLAND_DATA_DIR@/scripts/launch-waybar.sh
