exec-once = @HYPRCAT_DATA_DIR@/scripts/session-env.sh
exec-once = @HYPRCAT_DATA_DIR@/scripts/launch-hyprpaper.sh
exec-once = @HYPRCAT_DATA_DIR@/scripts/launch-swaync.sh
exec-once = @HYPRCAT_DATA_DIR@/scripts/launch-waybar.sh
