exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr-material3/scripts/launch-hyprpaper.sh
exec-once = ~/.config/hypr-material3/scripts/launch-swaync.sh
exec-once = ~/.config/hypr-material3/scripts/launch-waybar.sh
