$m3_primary = rgb(cad6ff)
$m3_secondary = rgb(89dceb)
$m3_surface = rgb(1e1e2e)
$m3_surface_dim = rgb(181825)
$m3_text = rgb(cdd6f4)
$m3_muted = rgb(9399b2)
$m3_error = rgb(f38ba8)

layerrule = blur on, match:namespace anyrun
layerrule = blur on, match:namespace rofi
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace anyrun
layerrule = ignore_alpha 0, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
